#!/bin/bash
cd ~/Desktop/2sprout/2sprout\ API/
rm libsprout.a
g++ -c *.cpp
rm libsprout.a
ar cq libsprout.a *.o

sudo cp libsprout.a /usr/local/2sprout/lib
cd ../Test\ Applications/C++\ test\ app/
g++ -L/usr/local/2sprout/lib -lsprout -o api test.cpp 

