#!/bin/bash

cd ~/Desktop/2sprout/2sprout\ API/
cp sprout.c sprout.h sprout.i ~/Desktop/2sprout/2sprout\ API/Dynamic\ libraries/Python/2.5.4/
cp sprout.c sprout.h sprout.i ~/Desktop/2sprout/2sprout\ API/Dynamic\ libraries/Python/2.6.2/
cp sprout.c sprout.h sprout.i ~/Desktop/2sprout/2sprout\ API/Dynamic\ libraries/Python/3.0
cp sprout.c sprout.h sprout.i ~/Desktop/2sprout/2sprout\ API/Dynamic\ libraries/C#/
cp sprout.c sprout.h sprout.i ~/Desktop/2sprout/2sprout\ API/Dynamic\ libraries/Java/
cp sprout.c sprout.h sprout.i ~/Desktop/2sprout/2sprout\ API/Dynamic\ libraries/Ruby/
cp sprout.c sprout.h sprout.i ~/Desktop/2sprout/2sprout\ API/Dynamic\ libraries/C++/




cd ~/Desktop/2sprout/2sprout\ API/Dynamic\ libraries/Python/2.5.4/
swig -python sprout.i
gcc -c *.c sprout_wrap.c -I/usr/include/python2.5 -I/usr/lib/python2.5
gcc -bundle -flat_namespace -undefined suppress -arch i386  -o _sprout.so *.o
cp sprout.py _sprout.so ~/Desktop/2sprout/2sprout\ API/Test\ Applications/Python\ test\ app/2.5.4/


cd ~/Desktop/2sprout/2sprout\ API/Dynamic\ libraries/Python/2.6.2/
swig -python sprout.i
gcc -c *.c sprout_wrap.c -I/usr/local/include/python2.6 -I/usr/local/lib/python2.6
gcc -bundle -flat_namespace -undefined suppress -arch i386  -o _sprout.so *.o
cp sprout.py _sprout.so ~/Desktop/2sprout/2sprout\ API/Test\ Applications/Python\ test\ app/2.6.2/


cd ~/Desktop/2sprout/2sprout\ API/Dynamic\ libraries/C#/
swig -csharp sprout.i
gcc -FPIC *.c sprout_wrap.c
gcc -bundle -flat_namespace -undefined suppress -arch i386 *.o -o libsprout.so
cp sproutPINVOKE.cs sprout.cs libsprout.so ~/Desktop/2sprout/2sprout\ API/Test\ Applications/C#/
cd ~/Desktop/2sprout/2sprout\ API/Test\ Applications/C#/ 
mcs test.cs sprout.cs sproutPINVOKE.cs



cd ~/Desktop/2sprout/2sprout\ API/Dynamic\ libraries/Java/
swig -java sprout.i
gcc -c -FPIC *.c
gcc -c -FPIC sprout_wrap.c -I/System/Library/Frameworks/JavaVM.framework/Versions/1.5.0/Headers 
gcc -bundle -flat_namespace -undefined suppress -arch i386  -o libsprout.so *.o
cp sproutJNI.java sprout.java libsprout.so ~/Desktop/2sprout/2sprout\ API/Test\ Applications/Java/
cd ~/Desktop/2sprout/2sprout\ API/Test\ Applications/Java/ 
javac test.java sprout.java sproutJNI.java


#cd ~/Desktop/2sprout/2sprout\ API/Dynamic\ libraries/C++/
#gcc -L/usr/local/2sprout/lib -lsprout -o api test.cpp 
#cp api sprout.h ~/Desktop/2sprout/2sprout\ API/Test\ Applications/C++\ test\ app/


cd ~/Desktop/2sprout/2sprout\ API/Dynamic\ libraries/Ruby/
swig -ruby sprout.i
gcc -c *.c sprout.h 
gcc -FPIC -c sprout_wrap.c -I/Developer/SDKs/MacOSX10.5.sdk/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin9.0 
gcc -bundle -flat_namespace -undefined suppress -arch i386 -lz *.o -o sprout.bundle
cp sprout.bundle ~/Desktop/2sprout/2sprout\ API/Test\ Applications/Ruby\ test\ app/
