/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class sprout {
  public static String jsonGetMember(String json, String key) {
    return sproutJNI.jsonGetMember(json, key);
  }

  public static boolean jsonHasKey(String json, String key) {
    return sproutJNI.jsonHasKey(json, key);
  }

  public static String getSproutItem() {
    return sproutJNI.getSproutItem();
  }

}
