/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class sprout {
  public static string jsonGetMember(string json, string key) {
    string ret = sproutPINVOKE.jsonGetMember(json, key);
    return ret;
  }

  public static bool jsonHasKey(string json, string key) {
    bool ret = sproutPINVOKE.jsonHasKey(json, key);
    return ret;
  }

  public static string getSproutItem() {
    string ret = sproutPINVOKE.getSproutItem();
    return ret;
  }

}
