/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class sprout {
  public static int startFeed() {
    int ret = sproutPINVOKE.startFeed();
    return ret;
  }

  public static int stopFeed() {
    int ret = sproutPINVOKE.stopFeed();
    return ret;
  }

  public static int getFeed() {
    int ret = sproutPINVOKE.getFeed();
    return ret;
  }

  public static string getSproutItem() {
    string ret = sproutPINVOKE.getSproutItem();
    return ret;
  }

}
